## Import Packages
* numpy - package for scientific computing with Python
* seaborn - visualization library based on matplotlib, used here for importing the iris dataset.
* train_test_split - Split arrays or matrices into random train and test subsets.

In [1]:
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split

## Import keras packages
* Sequential - basic keras model composed of a linear stack of layers.
* Dense - a regular densely-connected NN layer.
* Activation - Activations can either be used through an Activation layer, or through the activation argument
* np_utils - Converts a class vector (integers) to binary class matrix.

In [2]:
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.utils import np_utils

Using TensorFlow backend.


## Examine the dataset
* load the iris dataset from seaborn
* explore the dataset using head and shape

In [3]:
iris = sns.load_dataset("iris")

In [4]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
iris.shape

(150, 5)

## Preprocess the dataset
* split the dataset into x and y values, with all flower features in x and corresponding species names in y.
* use the train_test_split method to split x an y randomly into train and test datasets. Argumets are :
    * sequence of indexables with same length / shape.
    * test_size : represent the proportion of the dataset to include in the test split.
    * train_size : represent the proportion of the dataset to include in the train split.
    * random_state : the seed used by the random number generator
* perform one hot encoding on the categorical value. 

In [6]:
X = iris.values[:, :4]
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3.0, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.0, 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5.0, 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.0, 1.4, 0.1],
       [4.3, 3.0, 1.1, 0.1],
       [5.8, 4.0, 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1.0, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5.0, 3.0, 1.6, 0.2],
       [5.0, 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
y = iris['species']
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [8]:
train_data_X, test_data_X, train_data_y, test_data_y = train_test_split(X, y, train_size=0.5, test_size=0.5, random_state=0)

In [9]:
train_data_X

array([[4.6, 3.1, 1.5, 0.2],
       [5.9, 3.0, 5.1, 1.8],
       [5.1, 2.5, 3.0, 1.1],
       [4.6, 3.4, 1.4, 0.3],
       [6.2, 2.2, 4.5, 1.5],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.9, 4.2, 1.3],
       [4.8, 3.0, 1.4, 0.1],
       [7.1, 3.0, 5.9, 2.1],
       [6.9, 3.2, 5.7, 2.3],
       [6.5, 3.0, 5.8, 2.2],
       [6.4, 2.8, 5.6, 2.1],
       [5.1, 3.8, 1.6, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [6.5, 3.2, 5.1, 2.0],
       [6.7, 3.3, 5.7, 2.1],
       [4.5, 2.3, 1.3, 0.3],
       [6.2, 3.4, 5.4, 2.3],
       [4.9, 3.0, 1.4, 0.2],
       [5.7, 2.5, 5.0, 2.0],
       [6.9, 3.1, 5.4, 2.1],
       [4.4, 3.2, 1.3, 0.2],
       [5.0, 3.6, 1.4, 0.2],
       [7.2, 3.0, 5.8, 1.6],
       [5.1, 3.5, 1.4, 0.3],
       [4.4, 3.0, 1.3, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.5, 2.3, 4.0, 1.3],
       [6.8, 3.2, 5.9, 2.3],
       [7.6, 3.0, 6.6, 2.1],
       [5.1, 3.5, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.7, 2.8, 4.5, 1.3],
       [6.6, 3

In [10]:
train_data_y

3          setosa
149     virginica
98     versicolor
6          setosa
68     versicolor
          ...    
9          setosa
103     virginica
67     versicolor
117     virginica
47         setosa
Name: species, Length: 75, dtype: object

### Perform one-hot encoding
* np.unique() - Returns the sorted unique elements of an array.
* return_inverse - if True, returns the indices of the unique array that can be used to reconstruct the array.
* to_categorical - Converts a class vector (integers) to binary class matrix. Arguments are class vector to be converted into a matrix and the total number of classes.
* Identify the unique values and all the places in the array where each of them occurs. This will give us an array of integers with each unique value identified by a unique integer. Use the to_categorical method to replace the integer encoded variable with a new binary variable for each unique integer value.

In [11]:
def one_hot_encoder(array):
    unique_values, indices = np.unique(array, return_inverse=True)
    
    print("Unique values: ", unique_values)
    print("Indices: ", indices)
    
    one_hot_encoded_data = np_utils.to_categorical(indices, len(unique_values))
    
    return one_hot_encoded_data

In [12]:
ohe_train_data_y = one_hot_encoder(train_data_y)

Unique values:  ['setosa' 'versicolor' 'virginica']
Indices:  [0 2 1 0 1 2 1 0 2 2 2 2 0 0 2 2 0 2 0 2 2 0 0 2 0 0 0 1 2 2 0 0 0 1 1 0 0
 1 0 2 1 2 1 0 2 0 2 0 0 2 0 2 1 1 1 2 2 1 1 0 1 2 2 0 1 1 1 1 0 0 0 2 1 2
 0]


In [13]:
ohe_test_data_y = one_hot_encoder(test_data_y)

Unique values:  ['setosa' 'versicolor' 'virginica']
Indices:  [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1 1 2 0 2 0 0 1 2 2 2 2 1 2 1 1 2 2 2 2 1 2 1 0 2 1 1 1 1 2 0 0 2 1 0 0
 1]


In [14]:
print(ohe_train_data_y)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


## Build the model
* Define a sequential model
* Add a dense layer with 16 neurons and relu activation. Set the input shape to 4 i.e. the number of feature inputs.
* Add the output layer. Set the number of neurons to 3 which is the number of unique classes and the activation to softmax.  
* Compile the model. Set the optimizer as adam and loss function as categorical_crossentropy as we're doing a classification and set metrics to accuracy to monitor the accuracy value over training.
* Train the model ovber 10 epochs with a batch size of 2. Vary the number of epochs and batch size to tune the model.

In [15]:
model = Sequential()

In [16]:
model.add(Dense(16, input_shape=(4,),name='Input_Layer',activation='relu'))

In [17]:
model.add(Dense(3,name='Output_Layer',activation='softmax'))

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Input_Layer (Dense)          (None, 16)                80        
_________________________________________________________________
Output_Layer (Dense)         (None, 3)                 51        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=["accuracy"])

In [20]:
model.fit(train_data_X, ohe_train_data_y, epochs=50, batch_size=5, verbose=1)

Epoch 1/50
75/75 [==============================] - 3s 37ms/step - loss: 1.7265 - accuracy: 0.4133
Epoch 2/50
75/75 [==============================] - 0s 3ms/step - loss: 0.8176 - accuracy: 0.7467
Epoch 3/50
75/75 [==============================] - 0s 1ms/step - loss: 0.7283 - accuracy: 0.7600
Epoch 4/50
75/75 [==============================] - 0s 1ms/step - loss: 0.6786 - accuracy: 0.7467
Epoch 5/50
75/75 [==============================] - 0s 1ms/step - loss: 0.6197 - accuracy: 0.7333
Epoch 6/50
75/75 [==============================] - 0s 1ms/step - loss: 0.6021 - accuracy: 0.7067
Epoch 7/50
75/75 [==============================] - 0s 1ms/step - loss: 0.5584 - accuracy: 0.7467
Epoch 8/50
75/75 [==============================] - 0s 2ms/step - loss: 0.4947 - accuracy: 0.8267
Epoch 9/50
75/75 [==============================] - 0s 1ms/step - loss: 0.4856 - accuracy: 0.8000
Epoch 10/50
75/75 [==============================] - 0s 3ms/step - loss: 0.4545 - accuracy: 0.8133: 0s - loss: 0.4695

## Test model accuracy
* evaluate() - Returns the loss value & metrics values for the model in test mode.
* Pass in the test data and its target labels for measuring the accuracy.


In [21]:
loss, accuracy = model.evaluate(test_data_X, ohe_test_data_y, verbose=0)

In [22]:
print("Loss = {:.2f}".format(loss))

Loss = 0.25


In [23]:
print("Accuracy = {:.2f}".format(accuracy))

Accuracy = 0.95
